### ISSUE TITLE
Fix names in MatchState enum

### ISSUE THREAD

**Issue by Igorbek** [yuriyoleynikov/YoTennis#5]
From [my comment](https://github.com/yuriyoleynikov/YoTennis/pull/2#discussion_r94253109) in #2:

"
Ok, I meant you would rename `BeginTiebreak` to `BeginningTiebreak`.
Now you still have inconsistency:
_verb + object_: `BeginGame`, `BeginTiebreak`
_gerund [+ object]_: `Drawing`, `PlayingGame`, `ChangingSides`, `PlayingTiebreak`, `ChangingSidesOnTiebreak`
_adjective_: `Completed`
_adjective phrase_: `NotStarted`

From the language perspective, both _gerunds_ and _adjectives_ are _adjective phrases_. So only form with a _verb_ is inconsistent. Note the proper spelling: _Begi**nn**ing_.
"

Please fix and create a PR

**Comment by yuriyoleynikov** [comment]
Closed
